name: Marketing
favicon: null
layout_spectrum: 0.47220329265110195
typography_spectrum: 0.8498817747458816
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2639066558331251
  lightness: 0.36446492397226393
  saturation: 0.21748310257680714
  rhythmicContrast: 0.05303588812239468
purpose: []
